# Generated by Django 2.2.24 on 2021-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('updated_at', models.BigIntegerField()),
                ('created_at', models.BigIntegerField()),
            ],
        ),
    ]
